### ISSUE TITLE
I am receiving an issue and I have no idea what this mean 

### ISSUE THREAD

**Issue by jared16292** [NCATComp410/comp410_summer_2022#23]
! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/jared16292/comp410_summer_2022.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by claesmk** [comment]
You should be able to do a 'git pull' to resolve this
